### PR TITLE
Support for VS2022

### LINKED ISSUE #5: Can this be updated to support Visual Studio 2022 Release?

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/mayerwin/vs-debug-single-thread/issues/5 (I Hope).

### CODE REVIEW

**Comment by mayerwin** [comment]
Thanks, have you tested this?

**Comment by SeppPenner** [comment]
> Thanks, have you tested this?

Hi, I'm testing it right now and I guess it doesn't work yet... I'm also not sure yet if this would break the support for VS2019 and so on... Give me a bit time and I will check :)

**Comment by SeppPenner** [comment]
@mayerwin Do you by any chance have an idea why I needed to remove the things from DebugSingleThread/DebugSingleThread.csproj to get it to compile properly?

**Comment by SeppPenner** [comment]
It doesn't work yet and I'm still playing around. Seems like VS2022 has changed a lot of API interop stuff somehow...

**Comment by mayerwin** [comment]
> @mayerwin Do you by any chance have an idea why I needed to remove the things from DebugSingleThread/DebugSingleThread.csproj to get it to compile properly?

It is not a trivial migration for sure:
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by SeppPenner** [comment]
> from

Yes, I've already seen the document but have no idea how to multi-target multiple VS versions easily. There is a way, but I'm not sure if it works yet. I will play around a bit more and tell you if I find some solution here.

**Pull request closed without merging**
